### ISSUE TITLE
Pre-receive hook script for the PR's

### ISSUE THREAD

**Issue by lucasravy** [bancodobrasil/stop-analyzing-embed#31] opened 2020-07-09 00:46 UTC
:grin: Howdy!

I have notice that one of the contributors is missing both on avatars and on the collaborators' page, although their commits can be seen via `git log` command. I think I know what happened here: we can see that the pattern of some commits (author's info) is unknown by Github,  it seems like this is possibly a corporative standard and this is pretty common for us developers who use git for work and for personal projects (image bellow). To make it easy to identify this kind of problems, what do you guys think about creating a pre-receive hook script for PR's and validate the authors’ pattern from commits? Is it possible?

![gitlog](https://user-images.githubusercontent.com/10381513/86983916-81b0eb80-c163-11ea-8dc5-b061642cd611.png)

Best regards :grinning:

**Comment by tiagostutz** [comment] 2020-07-11 13:49
That's a great ideia! Would you like to grab this @lucasravy ? Or maybe you @eduardomrodrigues ?

**Comment by eduardomrodrigues** [comment] 2020-07-12 18:10
That's really great idea, @lucasravy! Can I get in?
Just a single doubt, what kind pattern of  user's email  will we use?
Thank you!

**Comment by tiagostutz** [comment] 2020-07-13 11:47
@eduardomrodrigues  to be fare I really don't know an easy way... if it is possible, the hook could check the forks of the project (like https://github.com/bearcub3/stop-analyzing-embed/network/members) and then check whether the commiter's e-mail is present in the list of users that forked the repo. 

Maybe there's some solution/hook that already addresses this issue, but if there's not, you could build this on your own user, building a great README and maybe as a Poppins project, welcoming new contributors, hun?

**Comment by eduardomrodrigues** [comment] 2020-07-13 19:17
@tiagostutz, that's a good way to test my skills! Thank's for opportunity!
I'm on it

**Comment by lucasravy** [comment] 2020-07-13 21:44
Hey fellows!

I was looking for some info to help with this issue and I found an article (link bellow). I could be wrong, but it seems to be possible only in an enterprise version for GitHub and I don't know if that is the case.

https://docs.github.com/en/enterprise/2.19/admin/developer-workflow/about-pre-receive-hooks

**Comment by eduardomrodrigues** [comment] 2020-07-14 11:09
Thank's a lot, @lucasravy! I'll follow the @tiagostutz ideia.
I'll create a node module with GitHub API integration.
Here:
https://github.com/eduardomrodrigues/git-check-author

**Comment by eduardomrodrigues** [comment] 2020-07-14 22:26
Good night, my friends! 
My solution is under construction but now, I have a big issue, with GitHub API I can take all project members, with this member ID, I can get all user info. The problem is this email is a private property by default, so I can't achieve it. 
Other solution is take the user email from ./git in filesystem but, this works only if the user set this without --global parameter
Any sugestions?


Thank you!

**Comment by tiagostutz** [comment] 2020-07-16 19:51
Hi @eduardomrodrigues I'm thinking here... big issue! ehhehehehehe... 
@flaviostutz any thoughts?

**Comment by tiagostutz** [comment] 2020-07-24 23:16
@eduardomrodrigues I was thinking here... what about building a bot that is "hooked" on PRs and it checks in
https://github.com/bancodobrasil/stop-analyzing-embed/graphs/contributors whether the person that opened the PR is listed as a contributor and, if not, it creates an issue on the project reporting this.
Actually, it is almost the same path @lucasravy did to bring this issue here.

What do you think?

-----

/please-review-my-english

_PS - this /please-review-my-english "command" is something new we are testing which consists in asking volunteers to review your message and give suggestions on how to improve it. The idea is to make open source a great opportunity to learn english as well. The volunteer will review only the "tagged" message and not the entire thread._

**If you want you english to be reviewed, just place this command (`/please-review-my-english`) in your message**

**Comment by eduardomrodrigues** [comment] 2020-07-24 23:24
@tiagostutz , for me will be a great quest! I'm on it! Thank's
_PS: if my messages passed thru any english correction algorithm, let's pray for this poor processor_

**Comment by giteshk11** [comment] 2020-07-31 11:49
i think its better to have github action isn't?

**Comment by tiagostutz** [comment] 2020-07-31 14:30
IMHO, althought not having the contribution correctly registered is a problem for the project, this is not a functional problem with the PR itself and this tool won't be focusing on the code or the PR aspects itself, but will be checking other aspects of the repo, that's why I think this don't need to be necessary a GitHub Action. But if GitHub Actions is the easiest way to do so, I don't see a problem in using it. 
The only thing to be noticed is that a GitHub Action using the GITHUB_TOKEN is not able to post a comment when the PR is made from a Fork. This could be a problem, though.

**Comment by eduardomrodrigues** [comment] 2020-08-01 15:08
@tiagostutz, this discussion created this project: 
https://github.com/eduardomrodrigues/cool-bot

I'll hope to code a really cool BOT for GitHubbers, with your help, I will put all this functionalities inside it. I'll use Deno(because I want to learn)

What do you think?
@giteshk11 @lucasravy

**Comment by eduardomrodrigues** [comment] 2020-08-01 16:09
> @tiagostutz, this discussion created this project:
> https://github.com/eduardomrodrigues/cool-bot
> 
> I'll hope to code a really cool BOT for GitHubbers, with your help, I will put all this functionalities inside it. I'll use Deno(because I want to learn)
> 
> What do you think?
> @giteshk11 @lucasravy

Now, after some studies I realize what I want.
Let's create a GitHub App: https://developer.github.com/apps/
What do you think?

**Comment by tiagostutz** [comment] 2020-08-01 16:41
Hi @eduardomrodrigues ! Nice move dude!

I like the GitHub App ideia with GitHub Actions, just like @giteshk11 proposed in https://github.com/bancodobrasil/stop-analyzing-embed/issues/31#issuecomment-667081312 . 
I was thinking about that and changed my mind about not using that. I just don't think it should break the PR if there's this author problem because it can be a bit tricky to fix and could be a barrier to the contributor has his/her PR merged. But, if it would be an Action that only warns for this issue so the user can fix it for the next PR (or for that one if he wants), I think that's a really good scenario.

The only thing to keep your eye on is about GITHUB_TOKEN restrictions on commenting on Forked PRs (I'm contributing to a project and struggling with this right now, btw: https://github.com/single-spa/single-spa/issues/515).

In this thread, one of the guys said that this restriction will be resolved by september, according to https://github.com/github/roadmap/issues/75. Until then you could consider using https://github.com/actions/toolkit/blob/master/docs/commands.md#set-outputs as I'm going to use also or bring another option to that.

**Comment by eduardomrodrigues** [comment] 2020-08-01 17:15
Yes, @tiagostutz! Thank's for this explanation. My plan was gives this GitHub App Bot life, like our friend @giteshk11  suggests, and after made the english revisions hook.

Again, thank you so much for this advices!

**Comment by eduardomrodrigues** [comment] 2020-08-01 23:40
@tiagostutz, did you see this:
https://github.com/octokit/rest.js

**Comment by tiagostutz** [comment] 2020-08-02 22:07
Hi there, @eduardomrodrigues .!

I haven’t.!! Maybe @rafamarts and @finhaa may be interested in that resource. 

I’ll check it out also. Thanks for linking this here.! ✊🏻

**Comment by finhaa** [comment] 2020-08-03 00:21
Hey, @tiagostutz!

I had already seen this resource, there is even this [link](https://developer.github.com/v3/libraries/) that shows some libraries available for various languages.

**Comment by tiagostutz** [comment] 2020-08-03 11:57
Yep, It looked very useful for the GitHunter project. Have you guys thought about using this or is there limitations on that?

**Comment by finhaa** [comment] 2020-08-03 14:12
We can take this discussion to a code review. I don't remember the reasos why we didn't use theses libraries.

**Comment by eduardomrodrigues** [comment] 2020-08-05 00:01
Hi, all! In fact, I looked to this project [Probot](https://github.com/probot/probot), I liked the way these guys solved the authentication problem and their API is very simple. But they are making the new version of Probot with the new Octokit library version, the core of the system.
I'll start to help them contribute to the new beta version, make some codes, with luck.
I think this project can help us with our great English teacher BOT 
For anybody who wants to help, this is the issue:
[Make the beta greater again](https://github.com/probot/probot/pull/1274)

**Comment by tiagostutz** [comment] 2020-08-05 09:35
Awesome, @eduardomrodrigues .!
This issue is a “Great candidate” (hahahahaha) for open source friday if someone is looking for.

Can’t wait to see the results of this new version along with the English bot and the User account validation GutHub Action we are building here. Nice!

**Closed** 2021-03-01 14:34 UTC
Labels: first-timers-only, good first issue
